### ISSUE TITLE
autoplay is not looped

### ISSUE THREAD

**Issue by danielneubert** [warpcgd/vue-concise-slider#101]
**Hey there,**

I came across a problem with the autoplay function/option, when the slider is not looped.

Maybe there also is a configuration / setup that the autoplay function actually does exactly what i need. If so, feel free to help me out. ;D

### Items 1-5
![Slider Items 1-5](https://i.imgur.com/jns1FVp.png)

### Items 6-8
![Slider Items 1-5](https://i.imgur.com/1S3yLXs.png)

## The Idea / Problem

I would like to slide through the two pages with 8 items automatically with the autoplay option.

But since the Slider isn't looped (display bugs on the last page with the ghost-items) the autoplay ends at the last Slide with Items 6, 7 and 8. There is no "sliding back" automation to make it forward and backwards.

## Suggestion

I would like to have a configuration:

```js
// ...
autoplay: true,
autoplayDirection: 'both', // 'ltr', 'rtl', 'both'
// ...
```

**Comment by warpcgd** [comment]
@danielneubert 

Thank you for your feedback, but I am not very clear about your code structure and how to reproduce the problem, so please post your code. 
In addition, if autoplay wants to play in a loop, you need to set
```js
option: {
  loop: true,
  autoplay: 1000,
}
```
