### ISSUE TITLE
初始化延迟加载的图片的时候，发现克隆的是没有数据响应的组件，这里的逻辑是不是有问题

### ISSUE THREAD

**Issue by little-buddy** [warpcgd/vue-concise-slider#110]
https://github.com/warpcgd/vue-concise-slider/blob/2ba91151344e3b6a2f95f405af9e1b7dd98a0eb5/src/components/common/sliderWrapper.js#L2

**Comment by little-buddy** [comment]
没有任何问题，npm 安装的是3.4.4 版本的。才发现原来作者是直接 clone dom 来实现循环轮播的，这个逻辑简直太可怕了额...升级到4.x 就替换成 deepClone 模式了

**Comment by warpcgd** [comment]
- 3.x版本做的是html节点的clone

- 4.x版本做的是vue节点的clone，vue clone节点的方法没暴露出来，所以用的是一种偷鸡的方法，所以暂时放测试版本里面
