### ISSUE TITLE
Suggestion: Prevent document move only on specific swipe direction

### ISSUE THREAD

**Issue by hansy** [warpcgd/vue-concise-slider#131]
If I have a slider with`preventDocumentMove = true`, I cannot scroll if I swipe up/down on the slider. It would be nice if there was a conditional check to see if the swipe is vertical before disabling the document.

Perhaps the values for `preventDocumentMove` could be:

- `true` (prevent document move on any swipe; current behavior)
- `false` (document moves regardless of swipe; current behavior)
- `horizontalOnly` (prevent document move only on horizontal swipe)
- `verticalOnly` (prevent document move only on vertical swipe)

Instagram, for example, disables vertical scrolling if you swipe horizontally on their slider. But if you swipe vertically, you can scroll even if you swipe on the slider.

**Comment by warpcgd** [comment]
Thank you for your suggestion, I will add it in the next version
