### ISSUE TITLE
使用vue-cli单页面开发不知道如何使用

### ISSUE THREAD

**Issue by somnusnrlq** [warpcgd/vue-concise-slider#15]
首先我在页面中npm install vue-slider --save 
然后再页面中import 使用无效果。 看示例蒙蒙的 新手求指教

**Comment by hong-boy** [comment]
好像作者没有提供npm包

**Comment by warpcgd** [comment]
@somnusnrlq @hong-boy  npm 包发布了，地址在:https://www.npmjs.com/package/vue-concise-slider
