### ISSUE TITLE
bug? "slider" is not provided as an export

### ISSUE THREAD

**Issue by stauersbol** [warpcgd/vue-concise-slider#157]
Hi, I seem to have found a issue.

`Uncaught SyntaxError: The requested module '/node_modules/vue-concise-slider/dist/module.js' does not provide an export named 'slider'`

I have no idea, why and how this could be fixed.
Feel free to ask any questions for more info on this.

EDIT:
What I found was in the exportModule.js file. Second last line `export { slider, slideritem}`
I am also using version 4.2.5.

**Comment by warpcgd** [comment]
Hi, can you post the relevant code? How exactly are you citing it?
