### ISSUE TITLE
你好，能加上PC版点击上一页图标和下一页图标吗？

### ISSUE THREAD

**Issue by ys5678** [warpcgd/vue-concise-slider#16]

**Comment by warpcgd** [comment]
@ys5678  你好，上一页下一页，不再slider组件里面，是放在父级组件，随便自定义，可以看下案例
https://github.com/warpcgd/vue-concise-slider/blob/master/src/components/slider_basic.vue

**Comment by ys5678** [comment]
今天我已经做好了，非常感谢
