### ISSUE TITLE
run time 模式下 tempalte 不可用

### ISSUE THREAD

**Issue by 13716114946** [warpcgd/vue-concise-slider#17]

**Comment by warpcgd** [comment]
嗯？什么意思？

**Comment by UncleBill** [comment]
@warpcgd `runtime only` 模式的 vue 是不包含模版编译器的。`vue-concise-slider` 发布的文件里包含了模版字符串，需要转成 render function，才能兼容 `runtime-only` 模式。

![image](https://user-images.githubusercontent.com/1141198/29608180-ffc1131c-8825-11e7-8b2e-20f6f80697e5.png)

**Comment by warpcgd** [comment]
@UncleBill 目前没有将模板写在render里面

**Comment by UncleBill** [comment]
@warpcgd 可能我没说清楚。我的意思是，你需要写转成 `render()` 函数，这才是问题所在。
