### ISSUE TITLE
item为什么绑定不了click点击事件，我需要点击一个item时执行一些操作,你的slide事件办不到

### ISSUE THREAD

**Issue by lichunfanggg** [warpcgd/vue-concise-slider#22]

**Comment by warpcgd** [comment]
@lichunfanggg  [https://github.com/warpcgd/vue-concise-slider/issues/18](url)

**Comment by lichunfanggg** [comment]
好的，谢谢

**Comment by lichunfanggg** [comment]
试了<slider :pages="pages" :sliderinit="sliderinit" @itemClick="handle"/>
和<slider :pages="pages" :sliderinit="sliderinit" @click.native="handle"/>两种,都触发不了

**Comment by warpcgd** [comment]
@lichunfanggg 手机上测试的吗？

**Comment by lichunfanggg** [comment]
不是，chrome上试的

**Comment by warpcgd** [comment]
@lichunfanggg 试试手机上呢，我记得我测试过，如果还不行，下个版本我会开放新的接口来监听点击的

**Comment by lichunfanggg** [comment]
刚才试了，也是触发不了

**Comment by lichunfanggg** [comment]
let sliders = document.querySelectorAll('.slider-container .slider-item')
      for (let i = 0; i < sliders.length; i++) {
        sliders[i].addEventListener('click', function (e) {
          confirm()
        })
      }
用这种在电脑和手机也试一下，touchstart就可以，click不行

**Comment by warpcgd** [comment]
@lichunfanggg 已经添加了tap事件
