### ISSUE TITLE
when updating props's value of pages, failed to trigger updating of element of templates!

### ISSUE THREAD

**Issue by wangjiangchuan** [warpcgd/vue-concise-slider#23]
when I use the 

## 'vue-concise-slider/src/components/slider.vue' 

component, the values of pages comes from the response data pulling from the server, so here is a problem: at the first time, when creating the component, there are no data coming from pages, after receiving the data from the server, we get the real value of pages, so props updates, I can see the log when updating the props, also logs from the updated function and beforeUpdate function of vue, however, the elements of the template fail to change any more, can you help to tackle this problem?

**Comment by wangjiangchuan** [comment]
when there is no data in pages,  console will output such warnings:
`[Vue warn]: Error in mounted hook: "TypeError: Cannot read property 'offsetLeft' of undefined"

found in

---> <Slider> at src/app/common/components/slider.vue`
Sure to receive such message, if there is no data, but it seems when we changed the value of pages, nothing update.

**Comment by warpcgd** [comment]
Hi wangjiangchuan,thanks for your issue,it's a BUG!!! to occur "offsetLeft" problem , i will solve it soon 。
when changing the value of pages , you should uesd [Mutation Methods](https://vuejs.org/v2/guide/list.html#Mutation-Methods);like this:
```html
this.someList.push({
    title: 'slidernew',
    style: {
      background: '#333',
      color: '#fff'
     }
 })
```

**Comment by wangjiangchuan** [comment]
Got it, thanks a lot! I should directly change the list itself instead of changing the reference of the pages. Thanks a lot.
