### ISSUE TITLE
slider后面会支持组件吗？作者说初衷只是想建立一个简单的幻灯片，但是如果能加上这个那就完美了，强烈建议加

### ISSUE THREAD

**Issue by ghost** [warpcgd/vue-concise-slider#31]

**Comment by warpcgd** [comment]
@hejiqing 支持组件的意思是？

**Comment by hejiqing** [comment]
就是幻灯片里面能放component

**Comment by warpcgd** [comment]
@hejiqing 现在幻灯片的遍历都是放到组件里面进行的，可以fork代码看下[slider_basic](https://github.com/warpcgd/vue-concise-slider/blob/master/src/components/slider_basic.vue)里面内容，也可以自己定义一个新的遍历组件，已经在里面嵌套自己需要的组件]
