### ISSUE TITLE
property 'offsetWidth' of undefined"

### ISSUE THREAD

**Issue by kv321vk** [warpcgd/vue-concise-slider#39]
just slide effect has no problem

**Comment by warpcgd** [comment]
@kv321vk  Hi, Can you describe the problem in detail, what is the configuration ?

**Comment by kv321vk** [comment]
Mobile terminal can't fixed width without access to the width of the parent. I think this is the problem

**Comment by kv321vk** [comment]
just set you demo in chrome develop Tools moblie module you can see the problem

**Comment by warpcgd** [comment]
![TEST](https://user-images.githubusercontent.com/19892562/35546970-665168da-05b1-11e8-82ec-75c4f31cd352.png)
I didn't find the wrong place. Is the address you are testing here ？ [demo](https://warpcgd.github.io/vue-concise-slider/demo/)

**Comment by guanjp** [comment]
@warpcgd  coverFlow的效果下会抱错
`[Vue warn]: Error in render: "TypeError: Cannot read property 'offsetWidth' of undefined"`

**Comment by warpcgd** [comment]
@guanjp  @kv321vk  Thank you for your issue. I've solved the problem.
