### ISSUE TITLE
安卓--a标签点击失效， IOS可以(轮播图片中)

### ISSUE THREAD

**Issue by WangShaoyu1** [warpcgd/vue-concise-slider#42]
<slider :pages="sliderDta" :sliderinit="sliderinit"></slider>

1. sliderDta:['<a href="www.baidu.com"><img src=""/></a>']
2.sliderinit:{
   currentPage: 0,
          thresholdDistance: 100,
          thresholdTime: 500,
          loop: true,
          infinite: 1,
          slidesToScroll: 1,
          direction: 'horizontal',
          autoplay: '3000',
          duration: '1000'
}

**Comment by warpcgd** [comment]
需要使用a标签进行跳转吗？

**Comment by WangShaoyu1** [comment]
需要，每个轮播图片可以进行 点击，代表一个活动详情。a标签 包着 img标签

**Comment by warpcgd** [comment]
@WangShaoyu1 写在tap事件里进行跳转吧
