### ISSUE TITLE
How to pass props to child components

### ISSUE THREAD

**Issue by RobertSmart** [warpcgd/vue-concise-slider#43]
Hi,

I'm trying to use this for a project, but I can't work out how to pass props into a dynamically loaded component. 

I can import the component using a normal import statement 

import panel from './panel.vue'

And I can use the panel as the component  for each page

data() {
    return {
      pages: [
        {
          component: panel
        },
        {
          component: panel
        }
      ],

But, how do I actually pass any data down into the component?

**Comment by warpcgd** [comment]
@RobertSmart Hi ,
thanks for your issue , I've updated the file，now you can use props in the component ，like this : 
```
{
    component: {
      props: ['item', 'sliderinit', 'pages'],
      data () {
        return {
          img: 'src/img/testimg-1.jpg'
        }
      },
      mounted () {
        console.log(this.item)
      },
      template: '<div><img style="width: 100%" :src="img" /><p style="position: absolute; margin: 0; right: 10px; bottom: 10px; font-size: 16px;">test1</p></div>'
    }
  }
```
