### ISSUE TITLE
当 slider 用于 iframe 内部的时候，鼠标先移上去，再移出去就没法失去焦点了

### ISSUE THREAD

**Issue by sheldonzf** [warpcgd/vue-concise-slider#46]
It do not listen moveout event.

**Comment by tbuy** [comment]
@warpcgd @sheldonzf 
我上传了解决这个问题的分支
[代码地址](https://github.com/tbuy/vue-concise-slider/commit/da854b8a29464fccefef7570c61af407b1f379ed)
