### ISSUE TITLE
Set 'autoplay' value is 0, but slide will autoplay.

### ISSUE THREAD

**Issue by parkzzzer91** [warpcgd/vue-concise-slider#49]
If you move the slide to the next slide or move the slide to stop it and immediately generate an 'autoplayStop' event, the slide will move at a very high speed.

**Comment by warpcgd** [comment]
@parkzzzer91  Thanks for your issue，I'll deal with it as soon as possible

**Comment by warpcgd** [comment]
@parkzzzer91 done
