### ISSUE TITLE
在使用Coverflow时，报错

### ISSUE THREAD

**Issue by ahutyaoyj** [warpcgd/vue-concise-slider#50]
![image](https://user-images.githubusercontent.com/9247427/42562687-fa27e852-852e-11e8-8c03-a690b5705476.png)

**Comment by warpcgd** [comment]
父级的高度未设置呢，具体可以看看demo文件 https://github.com/warpcgd/vue-concise-slider/blob/master/src/demo/slider_coverFlow.vue
