### ISSUE TITLE
Cannot read property 'offsetLeft' of undefined

### ISSUE THREAD

**Issue by wukaMM** [warpcgd/vue-concise-slider#63]
你好，
幻灯片播放几秒钟之后，就会在控制台中出现这个错误，请大大看下，我是哪里配置的不对吗？
`options: {
          currentPage: 0,
          // thresholdDistance: 500,
          // thresholdTime: 100,
          autoplay: 1000,
          loop: true,
          // slidesToScroll: 1,
          // timingFunction: 'ease',
          speed: 1000,
          pagination: false,
        }`
还有，当我设置 speed： 1000 时，无缝循环滚动效果就无效了，从最后一张到第一张的时候，就是立刻变的，没有滚动效果。。
求指点~~

**Comment by warpcgd** [comment]
1.Cannot read property 'offsetLeft' of undefined，
说明此时currentpage大于item的最大值或小于item的最小值，loop会前后遍历一个item，
解决这个问题要查看下slideritem的数据是不是有的
2.speed和auto的数据相关联的，speed的值需要小于auto的值

**Comment by violetice** [comment]
问题已修复，请参阅#66

**Comment by sunsou1** [comment]
一开始正常， 为什么loop一段时间后会报这个错误呢？

**Comment by warpcgd** [comment]
@sunsou1 贴一下需求和项目的配置吧，好定位到问题

**Comment by sunsou1** [comment]
我这边其实没有做改动。
currentPage: 0,
thresholdDistance:100,
thresholdTime:500,
autoplay: 3000,
infinite:1,
loop: true,
direction:'horizontal',
loopedSlides: 1,
slidesToScroll: 1,
duration: 300,
timingFunction: 'ease',
pagination: false,
speed: 300,

<div style="width:100%;height:180px;margin-bottom: 10px">
  
  <slider ref="slider" :options="options" @slide='slide' @tap="onTap"  @init='onInit'>
    
    <slideritem  v-for="(item) in someList" :style="item.style" v-html="item.html"></slideritem>
    
  </slider>
</div>

填充数据是for循环填充4个
this.someList.push(
  {
    html: '<div style="background-color: rgba(0,0,0,0.5); width:100%;text-align:left;padding:3px 5px;font-size:15px !important;position:absolute;bottom:0px;left:0;font-weight:bold;">' + val.title + '</div>',
    style: {
      'background': 'url(' + val.icon + ')',
      'background-size': '100%',
      // 'text-shadow': '1px 1px 1px #000; padding:10px 0; color:#FFF; background:#CCC'
    }
  })

问题现象就是：
loop一段时间后Uncaught TypeError: Cannot read property 'offsetLeft' of undefined就会出现这个错误  然后就不能滑动了
需求：
其实就是想实现一个轮播图

**Comment by warpcgd** [comment]
@sunsou1 是进行了切换页面的操作后的报错吧

**Comment by violetice** [comment]
@sunsou1 
```
destroyed() {
      // 销毁时停止轮播，防止addActive报错
      this.clock().stop(this);
}
```

**Comment by sunsou1** [comment]
恩恩  切换页面会报。但是我这边测试的时候  停留再该页面不动 过个几分钟也会报

**Comment by warpcgd** [comment]
我今天来解决下

**Comment by sunsou1** [comment]
多谢

**Comment by violetice** [comment]
@warpcgd 作者大大，需要监听visibilitychange，页面不可见的时候需要停止轮播

**Comment by warpcgd** [comment]
@sunsou1  @violetice 已经添加了监听
