### ISSUE TITLE
第一个或者最后一个滑动露底问题

### ISSUE THREAD

**Issue by cgygd** [warpcgd/vue-concise-slider#65]
如图最后一个，按住向左边拖拽会有露底问题，请问有办法解决吗？
![1233](https://user-images.githubusercontent.com/2216048/49222130-04b18200-f416-11e8-8373-16cdf6cd1316.png)

**Comment by warpcgd** [comment]
@cgygd 明天更新一项新的配置，不让它漏底

**Comment by cgygd** [comment]
谢谢
