### ISSUE TITLE
有没有一个回调来处理滑动结束后的状态

### ISSUE THREAD

**Issue by 18784771** [warpcgd/vue-concise-slider#69]
我需要知道滑动结束后是哪一个index被激活了，并且我希望它是一个回调函数，是不是我漏掉了文档的内容？

**Comment by warpcgd** [comment]
slide这事件不满足吗？https://warpcgd.github.io/vue-concise-slider/#/zh-cn/config?id=slide

**Comment by 18784771** [comment]
原来如此,很好的设计，谢谢
