### ISSUE TITLE
我用了那个垂直的上下滑动的组件，点击事件点击不到元素

### ISSUE THREAD

**Issue by vivianus-chan** [warpcgd/vue-concise-slider#71]
就好像支付宝的年度账单，有几张图，上下滑动展示你的一年消费，我在其中一个slideitem里面有一个按钮，有点击事件，然后因为这个是通过zindex互相叠加堆放图片，即便是滑到了相应的图片，但是因为zindex不够大，点击事件用不了，请问有什么其他办法实现我的效果吗？

**Comment by warpcgd** [comment]
恩，最好写个demo出来，我方便找到问题的地方，看你描述，z-index和滑动效果不冲突

**Comment by warpcgd** [comment]
我理解这个需求，和z-index不冲突

第一页 z-index: 1.
第二页 z-index: 1.
第三页 z-index: 1. 如果有button，则设置为10

**Comment by vivianus-chan** [comment]
<slider ref="slider" :options="options" @slide='slideFn'>
      <slideritem v-for="(item,index) in someList" :key="index">
        <section :style="{'background-image': 'url('+item.bg+')'}">
          <div v-if="item.page==2">
          </div>
          <div v-else-if="item.page==3">
          </div>
          <div v-else-if="item.page==4">
          </div>
          <div v-else-if="item.page==5">
          </div>
          <div v-else-if="item.page==6">
          </div>
          <div v-else-if="item.page==7">
              <mt-button @click.native="saveFn">点击</mt-button>
          </div>
        </section>
      </slideritem>
    </slider>

我之前也通过改层级 以前达到了目的  但是后来发现 按钮所在的图片的上一张slideritem就不出现了

**Comment by vivianus-chan** [comment]
`<slider ref="slider" :options="options" @slide='slideFn'>
      <slideritem v-for="(item,index) in someList" :key="index">
        <section :style="{'background-image': 'url('+item.bg+')'}">
          <div v-if="item.page==2">
          </div>
          <div v-else-if="item.page==3">
          </div>
          <div v-else-if="item.page==4">
          </div>
          <div v-else-if="item.page==5">
          </div>
          <div v-else-if="item.page==6">
          </div>
          <div v-else-if="item.page==7">
              <mt-button @click.native="saveFn">点击</mt-button>
          </div>
        </section>
      </slideritem>
    </slider>`
我也试过手动修改图层去达到目的，我一共7张slideritem ，按钮在第7张里，但后来发现在改了z-index后，滑动的时候第6张就不出现了

**Comment by warpcgd** [comment]
```
<slider ref="slider" :options="options" @slide='slideFn'> 
    <slideritem v-for="(item,index) in someList" :key="index"> 
      <section :style="{'background-image': 'url('+item.bg+')'}"> 
        <div v-if="item.page==2"></div>
        <div v-else-if="item.page==3"></div> 
        <div v-else-if="item.page==4"></div> 
        <div v-else-if="item.page==5"></div>
        <div v-else-if="item.page==6"></div>
        <div v-else-if="item.page==7">
          <mt-button @click.native="saveFn">点击</mt-button>
        </div>
      </section>
    </slideritem>
  </slider>
```
结构是这样的吧，button比section z-index高就可以了
