### ISSUE TITLE
Using local npm package

### ISSUE THREAD

**Issue by tkaria** [warpcgd/vue-concise-slider#72]
First off - thanks for making this - it's super helpful. 

Not sure this is a bug but here's what I'm seeing:
1) I forked your repo 
2) Cloned it to my local project (vue-cli 3) in the src dir
3) Ran `npm install --save file:./vue-concise-slider` to install my cloned version locally
4) When importing (`import { slider, slideritem } from "vue-concise-slider"`) the export for `slider` and `slideritem` are not found. 

```
WARNING  Compiled with 2 warnings                                                                                                                                                       1:26:58 PM
 warning  in ./src/components/ImageSlider.vue?vue&type=script&lang=js&
"export 'slider' was not found in '../../vue-concise-slider/dist/module'
 warning  in ./src/components/ImageSlider.vue?vue&type=script&lang=js&
"export 'slideritem' was not found in '../../vue-concise-slider/dist/module'

  App running at:
  - Local:   http://localhost:8080/
  - Network: http://192.168.0.14:8080/
```

This seems to be because the exports that are needed are in `src\moduleExports.js` not in `dist\module.js`. 

Do you have a recommended approach to doing a local install or should I simply do:
`import { slider, slideritem } from "../../vue-concise-slider/src/exportModule";`

Please let me know if this requires clarification. Thanks!

**Comment by warpcgd** [comment]
you can import vue-concise-slider like this: 
```
   import { slider, slideritem } from './dist/module.js'
```
or ues this: 
```
   import slider from '../components/slider.vue'
   import slideritem from '../components/slider_item.vue'
```

**Comment by tkaria** [comment]
Thanks.  Maybe I wasn’t clear but module.js doesn’t export those symbols in the dist dir. only in the src/moduleExports
