### ISSUE TITLE
动态添加sliderItem,然后动态删除sliderItem，底部的小圆点没有响应式变化

### ISSUE THREAD

**Issue by qinghua5453** [warpcgd/vue-concise-slider#75]
动态添加sliderItem,然后动态删除sliderItem，底部的小圆点没有响应式变化

**Comment by qinghua5453** [comment]
隐藏小圆点后，当添加逐个添加sliderItem,然后逐个删除，再次滑动的时候，会报错。
Uncaught TypeError: Cannot read property 'offsetLeft' of undefined

**Comment by yizeruier1** [comment]
vue中 使用 无缝轮播  使用push 和 splice 改变数组的时候，  splice 删除数组前n项的时候，  会报错

**Comment by yizeruier1** [comment]
不知道怎么解决

**Comment by warpcgd** [comment]
@yizeruier1 需要重置下当前的轮播页
