### ISSUE TITLE
嵌套slider出现的异常问题

### ISSUE THREAD

**Issue by caoanlong** [warpcgd/vue-concise-slider#77]
父级slider为垂直方向，子级slider为水平方向；父级slider滑到第二页（子级slider在第二页），子级slider向左滑动到第一个页，继续向左滑动，居然将父级slider给滑下来到第一页去了!求解???

**Comment by warpcgd** [comment]
正常操作，不然会卡在当前页面，
可以通过配置nested控制
https://warpcgd.github.io/vue-concise-slider/zh/docs.html#nested

**Comment by caoanlong** [comment]
好的，已解决
