### ISSUE TITLE
切换路由

### ISSUE THREAD

**Issue by ai1shui** [warpcgd/vue-concise-slider#78]
当前路由引用slider组件使用，切换路由后再返回，slider组件会出现白屏，iPhone必现，Android手机大部分手机会出现（vivo手机，华为p20）出现白屏，另外可以提供refresh 事件吗

**Comment by warpcgd** [comment]
@ai1shui 估计是使用了定时滚动，切换路由的时候，定时器没停掉，文档里面有取消定制的方法，可以添加上https://warpcgd.github.io/vue-concise-slider/zh/docs.html#autoplaystop

**Comment by ai1shui** [comment]
没有使用定时器滚动，现在是手动滑动滚动的

**Comment by warpcgd** [comment]
@ai1shui 贴下部分代码吧，路由是原生路由还是vue的路由？

**Comment by ai1shui** [comment]
data() {
return {
options: {
                currentPage: 0,
                loop: true
            }
}
}
这个是index 页面，进入detail路由之后再返回，页面出现空白，引用的很简单

**Comment by warpcgd** [comment]
@ai1shui 用的vue路由吗

**Comment by ai1shui** [comment]
vue的路由

**Comment by warpcgd** [comment]
@ai1shui 刚刚测试了下，没发现白屏问题，路由我在代码里面写了一次优化，当页码不对的时候，会重新复位，所以，可以检查下是不是路由切换的时候，页面的数据清空了
```
watch: {
    // 解决route跳转问题
    '$route': function () {
      let that = this
      if (that.route) {
        let currentPage = that.data.currentPage
        let sliderLength = that.s_data.sliderLength
        that.s_data.transitionEnding = false
        if (currentPage < 0) {
          that.slide(0, 'animationnone')
        } else if (currentPage >= (that.pagenums || sliderLength)) {
          that.slide(sliderLength - 1, 'animationnone')
        } else {
          that.slide(currentPage, 'animationnone')
        }
        that.options.autoplay && that.clock().begin(that)
        that.route = false
      } else {
        that.route = true
        that.options.autoplay && that.clock().stop(that)
      }
    }
  },
```

**Comment by ai1shui** [comment]
好的，谢谢

**Comment by ai1shui** [comment]
哦，还有一个问题，slider做loop为true的时候第一个向最后一个滑动，或最后一个向第一个滑动的时候会出现白屏，这个有好的解决办法吗？

**Comment by warpcgd** [comment]
@ai1shui loop 为 true 应该不会出现白屏的情况，需要详细的看下代码
