### ISSUE TITLE
beforeDestroy  methods  error

### ISSUE THREAD

**Issue by guochengWang** [warpcgd/vue-concise-slider#82]
![image](https://user-images.githubusercontent.com/26064763/63749047-296f5300-c8dd-11e9-9078-e4340d824537.png)
![image](https://user-images.githubusercontent.com/26064763/63749062-33915180-c8dd-11e9-89fd-14cff4278f0c.png)

**Comment by warpcgd** [comment]
Thank you for your error, I will fix it after testing.

**Comment by rille111** [comment]
Also seeing this on every route change. 
However this slider is the best of all the sliders out there we think!

**Comment by warpcgd** [comment]
@rille111  THANKS

**Comment by rille111** [comment]
@warpcgd 
The errors seem to get thrown only when using ```preventDocumentMove: true,``` in the options.

More debug info: 
![image](https://user-images.githubusercontent.com/1324189/65497652-d9bf7f80-deba-11e9-849b-a894fa545e34.png)

**Comment by warpcgd** [comment]
@rille111 The problem is solved, updated to version 3.4.3

**Comment by rille111** [comment]
Wonderful @warpcgd - Fantastic work really!
