### ISSUE TITLE
tap

### ISSUE THREAD

**Issue by twoer** [warpcgd/vue-concise-slider#84]
` <slider ref="slider" :options="sliderData.options" @tap="sliderTap">
        <slideritem v-for="(item,index) in sliderData.list" :key="index">
          <img :src="item.coverUrl" alt="">
        </slideritem>
      </slider>`

tap 事件点好几次才偶尔执行一次，好奇怪，求解。

**Comment by warpcgd** [comment]
直接在sliderItem里面使用tap，不要在slider上面了
