### ISSUE TITLE
html inside slideritem is not wrap and not showing like center example

### ISSUE THREAD

**Issue by t0n1zz** [warpcgd/vue-concise-slider#85]
hello,
i am having problem, i am using the example in here [vue center](https://warpcgd.github.io/vue-concise-slider/demos/Center.html) and there is 2 problem i encountered:

1. it is not showing like in the example, where there is one slider in the center and on its lefft and right there is some visual showing there is still other slider on left and right
2. I tried to add html content inside slideritem and it works fine one large screen, but when i am on small screen then the html content is just being cut, not warp like most common thing happen.

```
<slider ref="slider" :options="slideOptions" >
	<slideritem v-if="birthdayDataStat == 'success' && birthdayData.length != 0" class="slideBirthday">
		<div>
				<h1 style="text-shadow: 2px 2px 4px #000000;">SELAMAT ULANG TAHUN KEPADA</h1>
				<span class="badge bg-warning-400 align-self-center ml-2 mb-1" v-for="data in birthdayData">
					<h2 class="mb-0">{{ 'CU ' + data.name + ' Ke - ' + data.usia }}</h2>
				</span>
				<br/>
				<h3 style="text-shadow: 2px 2px 4px #000000;">Semoga semakin maju berkembang dan bertumbuh bersama anggota</h3>
		</div>
	</slideritem>
	<!-- Customizable loading -->
	<div slot="loading">loading...</div>
</slider>
```

```
slideOptions: {
	currentPage: 0,
	speed: 300,
	itemAnimation: true,
	centeredSlides: true,
	thresholdDistance: 100,
	thresholdTime: 300,
	loopedSlides: 2,
	slidesToScroll: 1,
	loop: true
}
```

here is the screenshoot on mobile
![Screen Shot 2019-09-17 at 13 21 30](https://user-images.githubusercontent.com/6964548/65016672-0faab400-d94f-11e9-842d-7c5e8bdd3e70.png)

**Comment by warpcgd** [comment]
1.  SliderItem needs to use v-for to traverse nodes

```js
<slider ref="slider" :options="slideOptions" >
	<slideritem v-for="data in birthdayData" :key="data.name " v-if="birthdayDataStat == 'success' && birthdayData.length != 0" class="slideBirthday">
		<div>
				<h1 style="text-shadow: 2px 2px 4px #000000;">SELAMAT ULANG TAHUN KEPADA</h1>
				<span class="badge bg-warning-400 align-self-center ml-2 mb-1" >
					<h2 class="mb-0">{{ 'CU ' + data.name + ' Ke - ' + data.usia }}</h2>
				</span>
				<br/>
				<h3 style="text-shadow: 2px 2px 4px #000000;">Semoga semakin maju berkembang dan bertumbuh bersama anggota</h3>
		</div>
	</slideritem>
	<!-- Customizable loading -->
	<div slot="loading">loading...</div>
</slider>
```

**Comment by t0n1zz** [comment]
okay then how about the second issue? the content inside do not warp automatically, i tried to add row and col inside it but not working

**Comment by warpcgd** [comment]
warp automatically ？ What is the need ？ need slider adaptive screen ？
You need to adjust the css yourself, maybe you can pull away from a slider project, which is convenient for me to download and debug
