### ISSUE TITLE
beforeDestroy methods error

### ISSUE THREAD

**Issue by SingleJoy** [warpcgd/vue-concise-slider#87]
有关beforeDestroy methods error 报错的问题，能尽快解决并发包吗？谢谢。

**Comment by warpcgd** [comment]
好的，最近比较忙，中午更新

**Comment by SingleJoy** [comment]
因为项目用到这个插件，马上要上线了。辛苦了，多谢。

**Comment by warpcgd** [comment]
@SingleJoy 问题解决了，麻烦更新到3.4.3版本

**Comment by SingleJoy** [comment]
> 好的，最近比较忙，中午更新

已升级到最新版本，多谢。
