### ISSUE TITLE
Suggestion Responsive

### ISSUE THREAD

**Issue by gladson** [warpcgd/vue-concise-slider#88]
# Responsive

Based: [vue-owl-carousel](https://github.com/s950329/vue-owl-carousel#responsive)

Example : 

```json
:responsive="{
  0:{items:1,nav:false},
  600:{items:3,nav:true},
  1024:{items:4,nav:true},
}"
```

**Comment by warpcgd** [comment]
what?

**Comment by gladson** [comment]
> what?

To simplify a way of being responsive:
[vue-owl-carousel](https://github.com/s950329/vue-owl-carousel#responsive)

**Comment by warpcgd** [comment]
Thank you for your suggestions, I will refer

**Comment by pablo-iwg** [comment]
I support this feature, but it would just be easier to put a deep watch on the images object and resize/adjust based on the items passed in being changed.

**Comment by ibnujakaria** [comment]
any update for this?
