### ISSUE TITLE
当滚动的页数内容是动态获取时问题

### ISSUE THREAD

**Issue by pandxiong** [warpcgd/vue-concise-slider#89]
比如我先滚动的页数是10页，然后动态获取后的数据是8页或者不固定的页数，但是整个滚动的宽度或者高度还是第一次的，请问这个需要怎么解决呢？

**Comment by warpcgd** [comment]
@pandxiong  需要调用slider的slideTo方法，重新跳转到需要的展示的页面
https://warpcgd.github.io/vue-concise-slider/docs.html#slideto
